// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class Location
{
	private float latitude, longitude;
	
	public Location (float lng, float lat) 
	{
		longitude = lng;
		latitude = lat;
	}

	public string toString() {
		return string.Format ("location={0},{1}", longitude, latitude);
	}
}


