//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Bastion.Net
{

	public class NetRequest
	{
		public static int TYPE_PLAYER = 1;
		public static int TYPE_BASTION = 2;
		public static int TYPE_BATTLE = 3;
		public static int TYPE_ITEM = 4;
		public static int TYPE_ACTIVITY = 5;
		public static int TYPE_RECHARGE = 6;
		public static int TYPE_SYSTEM = 7;
		public static int TYPE_GM = 8;
		public static int TYPE_DEBUG = 9;

		private string serialNo;
		private int cmd;


		public NetRequest (int cmdID)
		{
			cmd = cmdID;

			serialNo = "aabbcc";
		}
	
		public string SerialNo {get {return serialNo;}}
		public byte[] Data {get { return Data; }}
		public int Cmd { get { return cmd; } }
	}
}

